version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-container
    networks:
      - ecommerce-network
    ports:
      - "80:80"

networks:
  ecommerce-network:
    external: true
